# Meta Data for SEO

# Homepage
title = "Henrik Söderlund"
titleSeparator = "-"
titleAddition = "Personal showcase"
description = "Personal showcase, explorations and ideas"

# Open Graph
images = ["henrik.png"]
ogLocale = "en_US"
titleHome = "Henrik Söderlund"

# Twitter Cards
twitterSite = "@henkis"
twitterCreator = "@henkis"

# Google Tag Manager
gtm_id = "6at4snq=aWQ9R1RNLUZXUjQ%3D&page=1" # Enter GTM container ID. This value is invalidated and redundant if the 'override_container_id' parameter below is set to true
gtm_id_noscript = "GTM-FWR4" # Enter GTM container ID. This is usually the same as gtm_id, but can in some cases be different.
gtm_datalayer = "basic" # set value to "basic" to build and populate a dataLayer array with unique page metadata
disable_gtm_in_development = false # This disables the GTM container on non-production environments - this setting invalidate the optional 'gtm environment' settings below.

# Server-side GTM related
gtm_endpoint = "load.sgtm.henriksoderlund.com" # enter hostname of GTM server-side endpoint in format sub.domain.tld. if unavailable leave blank as ""
use_custom_library_name = true # If this is set to true, ensure to set the gtm_library_name variable below and configure the GTM Custom Loader client template inside your ssGTM container
gtm_library_name = "dz4d7tyirczbv.js" # if using Simo Ahava's Custom GTM Loader template to enable changing the name of the GTM library, set the document name here. 
override_container_id = false # Set this to true only if Simo Ahava's Custom GTM Loader client template is used and configured to "Override Container ID" where you have added your preferred GTM container ID. Will drop the 'id=GTM=123456' part from the script src.

# Optional - Google Tag Manager Staging/Development Environment 
# enable or Disable the feature by setting the 'gtm_env_enable' flag to true
# create an additional "environment" from within the GTM Admin interface 
# extract the gtm_auth and gtm_preview query parameters from the 'src' URL query in the GTM snippet provided
# this gtm environment snippet activates whenever the HUGO_ENVIRONMENT variable is not set to 'production'

gtm_env_enable = true
gtm_env_param_gtm_auth = "dhxfPfIIp62NuQfRTdCd1w"
gtm_env_param_gtm_preview = "env-8"

# Other
wordCount = true

# JSON-LD
schemaType = "Person"
schemaName = "Henrik Söderlund"
schemaAuthor = "Henrik Söderlund"
schemaAuthorTwitter = "https://twitter.com/henkis/"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henriksoderlund/"
schemaAuthorGitHub = "https://github.com/henkis/"
schemaLocale = "en-US"
schemaLogo = "logo-henrik.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "henrik.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/henkis/"
schemaLinkedIn = "https://www.linkedin.com/in/henriksoderlund/"
schemaGitHub = "https://github.com/henkisdabro/"

# Chrome Browser
themeColor = "#fff"

# Images - Temporarily left in place for backward compatibility
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1280x720 Center" # normalize image size

# Footer
footer = "Powered by <a href=\"https://pages.cloudflare.com/\" target=\"_blank\" >Cloudflare Pages</a>, <a href=\"https://gohugo.io/\" target=\"_blank\" >Hugo</a>, and <a href=\"https://gethyas.com/\" target=\"_blank\" >Hyas</a>"

# Feed
copyRight = "Copyright (c) 2025 Henrik Söderlund"

# Alert
alert = false
alertDismissable = true
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"
